#! /bin/bash

pattern=/home/atom/Downloads/*torrent

function my_logger {
  echo $1 | tee >(logger -t "torrents-to-sb");
}

if ls $pattern 1> /dev/null 2>&1; then
  for file in $pattern; do
    my_logger "processing $file"
    scp "$file" sb:private/rtorrent/watch 1> /tmp/scp-result 2>&1
    if [[ $? != 0 ]]; then
      cat /tmp/scp-result | my_logger
      my_logger "scp failed for $file : $rc"
    else
      rm "$file"
      if [[ $? != 0 ]]; then
        my_logger "rm failed for $file : $rc";
      else
        my_logger "$file uploaded and removed successfully";
      fi
    fi
  done
else
  my_logger "nothing to do"
  exit 0
fi
